# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
name: waggylabs-dev

services:
  web:
    container_name: waggylabs-site-dev
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: waggylabs-site-dev
    command: ./start.sh
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file:
      - ./compose/dev/env.sh
    depends_on:
      - db


  db:
    container_name: waggylabs-db-dev
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=waggylabs_db
      - POSTGRES_USER=waggylabs_db
      - POSTGRES_PASSWORD=waggylabs_db

volumes:
  postgres_data:

