# Generated by Django 5.1.1 on 2024-09-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0002_create_sitepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_active_link_color',
            field=models.CharField(blank=True, default='', help_text='Specifies the color and opacity for the navigation bar active links. Leave empty (use "Clear" button) to use the default Bootstrap theme color.', max_length=25, verbose_name='Navigation bar active link color'),
        ),
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_color',
            field=models.CharField(blank=True, default='', help_text='Choose a specific color and opacity for the navigation bar. Leave empty (use "Clear" button) to use the default theme color.', max_length=25, verbose_name='Navigation bar color'),
        ),
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_hover_link_color',
            field=models.CharField(blank=True, default='', help_text='Specifies the color and opacity for the navigation bar links during hover. Leave empty (use "Clear" button) to use the default Bootstrap theme color.', max_length=25, verbose_name='Navigation bar hover link color'),
        ),
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_link_color',
            field=models.CharField(blank=True, default='', help_text='Specifies the color and opacity for the navigation bar links. Leave empty (use "Clear" button) to use the default Bootstrap theme color.', max_length=25, verbose_name='Navigation bar link color'),
        ),
    ]
